language: node_js
node_js:
  - '9'
  - '8'
  - '6'

after_success:
  - npm i -g semantic-release
  - semantic-release
  - yarn docs
  # needs proper NOW setup first
  # - yarn docs:publish

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email: false
